### ISSUE TITLE
Create Supplier Resource

### ISSUE THREAD

**Issue by sinduja123** [devops-suppliers/suppliers#4]
**As a** supplier manager 
**I need** to create a new supplier contact
**So that** I can add populate the supplier information such as name, address, phone number, category, email id of the supplier and collection of references of the products provided by the supplier

**Assumptions:**
*We* have the model attributes set up to create a supplier resource

**Acceptance Criteria:**

Given...
When I hit create a new supplier
Then I can add information about the supplier

**Comment by jp1130** [comment]
@sinduja123 do you think we only need ID, Name, and Address?

**Comment by jp1130** [comment]
all work is on branch titled 'supplier-resources'
