### ISSUE TITLE
Create UI for the application

### ISSUE THREAD

**Issue by jp1130** [devops-suppliers/suppliers#47]
**As a** developer
**I need** to create a UI for the supplier manager 
**So that** he/she can manage new/existing supplier resource

**Assumptions:**
* application is already running in the cloud

**Acceptance Criteria:**
...

Given the supplier manager needs to manage supplier catalog
When the supplier manager engages with the web UI
Then the back-end is connected to the web page 
....

---EXAMPLE---
Make the hit counter persistently survive service restarts

As a User
I need the hit counter to persist the last known count
So that I don't loose track of the count after the service is restarted

Assumptions:
	• We will use Redis as the persistent store
	• A Redis service from Bluemix should be used

Acceptance Criteria:
When	I	advance	the	hit	counter	to	2																
And		I	restart	the	hit	counter	services												
And		I	call	the	hit	counter	URL																				
Then	I	should	see	3	returned	from	the	service	

---End of EXAMPLE---

**Comment by jp1130** [comment]
Liyana - did you create the pull request then approved it yourself? Or how did you close it?

**Comment by liyana-fauzi** [comment]
I closed it and deleted the branch because I wanted to make more changes.
I'll send a pull request again later today.

So, it's not really "closed" closed  but more of a cancel.

**Comment by jp1130** [comment]
Should this be in the DONE section not CLOSED? We are not moving things to CLOSED until we are done with the sprint.
