### ISSUE TITLE
Read a Supplier

### ISSUE THREAD

**Issue by OliviaJacopetti** [devops-suppliers/suppliers#53]
As a Supplier Manager
I need a RESTful supplier catalog service
So that I can keep track of all my suppliers and their products

Assumptions:

UI for the application exist
BDD .feature file and accompanying steps.py files to test RESTful API from the outside in

Acceptance Criteria:
Scenario: Read a supplier
Given the following
| id | name | category | preferred |
| 1 | John | home & furnishing | True |
| 2 | Jane | apparel | True |
| 3 | Jack | apparel | True |

When I visit the "Home Page"
And I see the navigation bar
And I press the "Suppliers" button
Then I should see the list of suppliers

---EXAMPLE---
Add missing supplier to supplier list

As a User
I need the read the list of suppliers
So that I know which suppliers are missing and add missing suppliers

Assumptions:
• The supplier list will have a scroll functionality and pagination

Acceptance Criteria:
When I navigate to the supplier list
And I scroll through all suppliers
Then I should see all suppliers and their information

---End of EXAMPLE---

**Comment by jp1130** [comment]
READ = Retrieve on ID
