### ISSUE TITLE
Create Subordinate API to connect products with suppliers resource

### ISSUE THREAD

**Issue by liyana-fauzi** [devops-suppliers/suppliers#6]
**As a** Supplier Manager
**I need** to associate suppliers with their products and wholesale prices
**So that** I can query products associated with suppliers

**Assumptions:**
We have a RESTful API for the vendor resource
The products development team has an existing Restful API for the products resource

**Acceptance Criteria:**
When the Supplier Manager updates the product information in the product resource
Then the information is can be retrieved using the Query function for the subordinate API

**Comment by sinduja123** [comment]
Duplicate of Story 12 'Add model attributes for suppliers'
