### ISSUE TITLE
Add Dev Deployment Stage to the Pipeline

### ISSUE THREAD

**Issue by liyana-fauzi** [devops-suppliers/suppliers#66]
As a developer
I need to add a dev deployment stage to the CD pipeline
So that I can deploy to the dev space

Assumptions:
*I have the supplier app instance running in the cloud
*I have the github account linked to the toolchain
*Unit tests have passed

Acceptance Criteria:
Given I need to add a dev deployment stage to the CD pipeline
When the unit tests have passed
Then I can see the app in the dev space

**Comment by liyana-fauzi** [comment]
Edit manifest.yml file to run the pipeline

**Comment by sinduja123** [comment]
![image](https://user-images.githubusercontent.com/51089284/81135781-7a811d80-8f27-11ea-838c-9decbcd96777.png)
